name: SIPCONS
favicon: null
layout_spectrum: 0.24261
typography_spectrum: 0.82884
title: 'Soluciones Integrales de Pesaje y Control, SA de CV'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#09459b'
    - '#7abee7'
    - '#7295c7'
    - '#2c60aa'
  brandStrength: 0.9656091479118913
  lightness: 0.9197966391220689
  saturation: 0.9810113180428743
  rhythmicContrast: 0.7336656141560525
purpose: []
